market/urls.py
from django.urls import path, include
from django.contrib import admin
from marketplace import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_redirect),
    path('market/', include('marketplace.urls')),
]

marketplace/urls.py
from django.urls import path, re_path

from .views import StuffList

urlpatterns = [
    path('', StuffList.as_view(), name='home'),
    re_path(r'^search/', StuffList.as_view(), name='search_page'),
]

marketplace/models.py
from django.db import models
from taggit.managers import TaggableManager


class Stuff(models.Model):
    # поясню позже
    FORWARDING_CHOICES = (
        ('not', 'не указано'),
        ('yes', 'да'),
        ('no', 'нет'),
    )
    # если verbose_name идет первым аргументом - название писать не нужно.
    # Этот аргумент первый по умолчанию (исключение ForeignKey и т.п.)
    title = models.CharField('Название лота', max_length=100)
    description = models.TextField('Описание лота', max_length=2000)

    # В эти два поля просятся auto_now_add и auto_now, и тогда нет смысла их выводить в админке
    date = models.DateField('Дата добавления лота')
    modifatedate = models.DateField('Дата изменения лота', blank=True, null=True)
    price = models.IntegerField('Цена', null=True)

    # Для чисел - числовые типы (IntegerField, FloatField, DecimalField и т.д.)
    lastprice = models.CharField('Предыдущая цена лота', max_length=10, blank=True)
    # blank=True и null=True одновременно - лишне. Для текстовых полей юзай blank=True
    lot_url = models.CharField('Ссылка на лот', max_length=200, blank=True, null=True)
    forwarding = models.CharField('Возможность пересыла', choices=FORWARDING_CHOICES, default='not', max_length=5)
    # без приставки "stuff_" не очевидно чья subcategory имеется в виду?
    stuff_subcategory = models.ForeignKey('SubCategory', on_delete=models.SET_NULL, verbose_name='Категория', blank=True, null=True)
    tags = TaggableManager()
    tags_temp = models.CharField('ТЕСТОВЫЕ теги', max_length=500, blank=True, null=True)
    city = models.ForeignKey('City', on_delete=models.SET_NULL,  verbose_name='Город', blank=True, null=True)
    city_temp = models.CharField('ТЕСТОВЫЕ города', max_length=30, blank=True, null=True)
    visible = models.BooleanField('Видимость', default=False, null=True)
    moderated = models.BooleanField('Прошел модерацию', default=False, null=True)
    ondelete = models.BooleanField('На удаление', default=False, null=True)

    # 1. здесь точно должен быть не BooleanField? 2. default=0, зачем кавычки?
    marked_spam = models.IntegerField('Помечено как Спам', default='0', null=True)
    marked_bad_category = models.IntegerField('Помечено как неверная категория', default='0', null=True)
    marked_soldout = models.IntegerField('Помечено как продано', default='0', null=True)
    marked_insult = models.IntegerField('Помечено как оскорбление', default='0', null=True)

    vk_page_id = models.IntegerField('ID страницы лота', blank=True, null=True)
    vk_album_id = models.IntegerField('ID альбома с лотом', blank=True, null=True)
    vk_owner_id = models.IntegerField('ID владельца группы', blank=True, null=True)
    vk_user_id = models.IntegerField('ID владельца лота', blank=True, null=True)
    vk_image_tumb_url = models.CharField('URL tumbnail изображения', max_length=500, blank=True, null=True)
    vk_image_url = models.CharField('URL изображения', max_length=500, blank=True, null=True)
    vk_image_host = models.CharField('URL хоста изображения', max_length=100, blank=True, null=True)
    # user = models.ForeignKey('',on_delete=models.CASCADE)

    class Meta:
        ordering = ["title"]
        verbose_name = "Лот"
        verbose_name_plural = "Лоты"

    def __str__(self):
        return self.title


class User(models.Model):
    # user = models.ForeignKey()
    telephone = models.CharField('Телефон', max_length=10)
    email = models.EmailField('Email', null=True)
    vk_user_id = models.IntegerField('ID пользователя VK', null=True)

    class Meta:
        ordering = ["pk"]
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Category(models.Model):
    title = models.CharField('Название категории', max_length=100)

    class Meta:
        ordering = ["title"]
        verbose_name = "Категория товара"
        verbose_name_plural = "Категории товаров"

    def __str__(self):
        return self.title


class SubCategory(models.Model):
    title = models.CharField('Название подкатегории', max_length=100)
    category = models.ForeignKey('Category', verbose_name='Категория товара', on_delete=models.PROTECT)

    class Meta:
        ordering = ["title"]
        verbose_name = "Подкатегория товара"
        verbose_name_plural = "Подкатегории товаров"

    def __str__(self):
        return self.title


class City(models.Model):
    title = models.CharField('Город', max_length=100)

    # Вариации будешь через запятую в одну строку вносить? =)
    # Это делается с помощью ArrayField
    variations = models.CharField('Вариации названия города', max_length=1000)

    class Meta:
        ordering = ["title"]
        verbose_name = "Город"
        verbose_name_plural = "Города"

    def __str__(self):
        return self.title

marketplace/forms.py
from django import forms
from .models import City, SubCategory


class SearchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    text = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Название, описание'}), required=False)
    city = forms.ModelChoiceField(label='Город', queryset=City.objects.all(), required=False)
    stuff_subcategory = forms.ModelChoiceField(label='Категория', queryset=SubCategory.objects.all(), required=False)
    data_start = forms.DateField(label='Дата от', required=False)
    data_finish = forms.DateField(label='Дата до', required=False)
    price_start = forms.IntegerField(label='Цена от', required=False)
    price_finish = forms.IntegerField(label='Цена до', required=False)
    tags = forms.CharField(label='Тэги', required=False)

marketplace/views.py
from urllib import parse
from django.shortcuts import redirect
from django.views.generic import ListView
from marketplace.forms import SearchForm
from marketplace.models import Stuff
from marketplace.stuff_querybuilder import StuffQueryBuilder


def main_redirect(request):
    # tag='bar' - называется костыль
    return redirect('/market', tag='bar')


class StuffList(ListView):
    context_object_name = 'stuff_list'
    template_name = 'marketplace/stuff_list.html'
    paginate_by = 2

    def __init__(self, **kwargs):
        self.filter_params = {}
        super().__init__(**kwargs)

    def get_queryset(self):
        # try except придуман не для этого
        # stuff_list = Stuff.objects.all()
        # try:
        #     stuff_list = stuff_list.filter(tags__name=self.request.GET["tag"])
        # except KeyError:
        #     pass
        # return stuff_list
        params = dict(self.request.GET.items())
        if not params:
            return Stuff.objects.all()
        builder = StuffQueryBuilder(params)
        self.filter_params = builder.params
        return builder.query

    def get_context_data(self, **kwargs):
        # в python 3+ super можно вызывать без аргументов
        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm(initial=self.request.GET)
        context['filter_params'] = parse.urlencode(self.filter_params)
        return context

templates/marketplace/inc-paginator.html
<nav class="paginator" aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{{ filter_params }}&page={{ page_obj.previous_page_number }}">Назад</a>
            </li>
        {% endif %}
        {% for num in paginator.page_range %}
            <li class="page-item {% if page_obj.number != num %}disabled{% endif %}"><a class="page-link" href="?{{ filter_params }}&page={{ num }}">{{ num }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{{ filter_params }}&page={{ page_obj.next_page_number }}">Вперед</a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/marketplace/stuff_list.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stuff_list</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% static "css/paginator.css" %}">
    <link rel="stylesheet" href="{% static "css/stuff_list.css" %}">
    <link rel="stylesheet" href="{% static "css/stuff_filter.css" %}">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script>
        $(function() { $( "#id_data_start, #id_data_finish" ).datepicker({changeMonth: true, changeYear: true, yearRange: "1900:2030"}); });
    </script>
</head>
<body>
    <div class="stuff_list_wrapper">
        <h1>Список стаффа</h1>
        <table class="stuff_list">
            <tr>
                <th>{{ stuff.count }}</th>
                <th>Название лота</th>
                <th>Описание лота</th>
                <th>Категория</th>
                <th>Цена</th>
                <th>Пересыл</th>
                <th>Город</th>
                <th>Дата</th>
                <th>Теги</th>
            </tr>
            {% for stuff in stuff_list%}
                <tr>
                    <td >
                        <a href="{{ stuff.lot_url }}" target="_blank">
                            {% if stuff.vk_image_tumb_url %}<img src="{{ stuff.vk_image_tumb_url }}" alt="FOTO{{stuff.id}}" height="150" width="200">{% endif %}
                        </a>
                    </td>
{#                    инлайн стили выноси в css #}
                    <td style="width: 200px;"><a href="/admin/marketplace/stuff/{{ stuff.pk }}/change/" target="_blank">{{ stuff.title }}</a></td>
                    <td>{{ stuff.description }}</td>
                    <td>{{ stuff.stuff_subcategory }}</td>
                    <td>{{ stuff.price }}</td>
                    <td>{{ stuff.get_forwarding_display }}</td>
                    <td>{{ stuff.city }}</td>
                    <td style="width: 200px;">{{ stuff.date }}</td>
                    <td style="width: 200px;">
                        {% for tag in stuff.tags.names %}
                            <a href="{% url "home" %}?tag={{ tag|urlencode }}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
        {#                Был очень странный цикл. #}
        {#                {% with names=stuff.tags.names %}#}
        {#                    {% if names.count > 0 %}#}
        {#                        <p>Теги: {%for name in names %}{% if not forloop.first %}, {% endif %}#}
        {#                        <a href="{% url "home" %}?tag={{ name|urlencode }}">{{ name }}</a>{% endfor %}</p>#}
        {#                    {% endif %}#}
        {#                {% endwith %}#}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="stuff_filter">
        <h3>Фильтр:</h3>
        <form method="get" action="{% url "search_page" %}">
            {{ form }}
            <button class="stuff_filter_submit" type="submit">Найти</button>
        </form>
    </div>
    {% if is_paginated %}{% include "marketplace/inc-paginator.html" %}{% endif %}
</body>
</html>